CREATE TABLE
IF NOT EXISTS users
(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login text NOT NULL CHECK (login <> ''),
    password text,
    age integer,
    isDeleted: boolean
);

INSERT INTO users
    (login, password, age)
VALUES('Banabas', '121323', 23, false)

INSERT INTO users
    (login, password, age)
VALUES('Jonah', '102938', 27, false)

CREATE TABLE IF NOT EXISTS groups(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL CHECK (name <> ''),
    permission TEXT [],
    userId INTEGER REFERENCES users(id)
);

INSERT INTO groups(name, permission, userId)
    VALUES('firstGroup', '{READ, WRITE}', 1)