CREATE TABLE
IF NOT EXISTS users
(
    id VARCHAR(255) PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    login text NOT NULL CHECK (login <> ''),
    password text,
    age integer,
    isDeleted: boolean
);

INSERT INTO users
    (login, password, age)
VALUES('Banabas', '121323', 23, false)

INSERT INTO users
    (login, password, age)
VALUES('Jonah', '102938', 27, false)